ad                              |
| area_code                       |
| banner                          |
| bus                             |
| charter_invoice_relation        |
| charter_line_plan               |
| charter_line_plan_bus           |
| charter_line_plan_user          |
| charter_order                   |
| charter_payment                 |
| check_ticket_record             |
| coupon                          |
| coupon_event                    |
| driver                          |
| driver_gps                      |
| driver_line_relation            |
| driver_msg                      |
| edge                            |
| enterprise_balance              |
| enterprise_recharge_log         |
| enterprise_user                 |
| events                          |
| function_area                   |
| image_index                     |
| invoice                         |
| invoice_send_record             |
| line                            |
| line_demand                     |
| line_demand_copy                |
| line_intercity                  |
| line_intercity_relation         |
| line_route                      |
| line_school_relation            |
| line_station                    |
| line_station_copy               |
| line_statistic                  |
| line_statistic_daily            |
| line_statistic_month            |
| line_vote                       |
| linecrowdfunding                |
| lineinfo                        |
| lineplan                        |
| lineplan_bus                    |
| lineplan_calendar               |
| lineplan_canendar               |
| lineplan_evaluation             |
| lineplan_ticket                 |
| od                              |
| order_item                      |
| order_item_copy                 |
| order_payment                   |
| order_payment_copy              |
| org                             |
| push_user                       |
| refund_order                    |
| refund_order_copy               |
| refund_order_item               |
| refund_order_item_copy          |
| refund_order_serial_number      |
| refund_order_serial_number_copy |
| school                          |
| sign_code                       |
| site                            |
| sms_template                    |
| station                         |
| station_arrive_remind           |
| station_arrive_remind_over      |
| station_copy                    |
| station_time                    |
| stationupdate                   |
| suggestion                      |
| suggestion_type                 |
| system_error_log                |
| system_msg                      |
| ticket                          |
| ticket_copy                     |
| ticket_intercity                |
| ticket_inventory                |
| ticket_inventory_copy           |
| ticket_order                    |
| ticket_order_copy               |
| ticket_print                    |
| type_entry                      |
| user                            |
| user_admin                      |
| user_coupun                     |
| user_msg                        |
| version                         |
| wish_line_vote                  |
| wishline